# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sortxy <- function(x, y) {
    .Call(`_igraphUtils_sortxy`, x, y)
}

triadCensusCol <- function(A, attr, orbitClasses, triads) {
    .Call(`_igraphUtils_triadCensusCol`, A, attr, orbitClasses, triads)
}

