# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

benchmark <- function(excess, defect, num_nodes, average_k, max_degree, tau, tau2, mixing_parameter, overlapping_nodes, overlap_membership, nmin, nmax, fixed_range, verbose = FALSE) {
    .Call(`_netUtils_benchmark`, excess, defect, num_nodes, average_k, max_degree, tau, tau2, mixing_parameter, overlapping_nodes, overlap_membership, nmin, nmax, fixed_range, verbose)
}

mse <- function(adjList, deg) {
    .Call(`_netUtils_mse`, adjList, deg)
}

triadCensusCol <- function(outList, nbList, attr, k, lookup, nclass) {
    .Call(`_netUtils_triadCensusCol`, outList, nbList, attr, k, lookup, nclass)
}

